Fixes #1557, #1000
* Merge and cleanup @trevorsibanda's work on #1557 and #1000.
  Consolidate MySql tests, resolve merge conflicts with master
* Trim the BigDecimal default value string to remove trailing spaces from Oracle
  default value.
* Remove the OracleProfile specific default value handling - this is now done in the
  JdbcModelBuilder and is unnecessary.
* Add test for Oracle BigDecimal default value.

Tests fail for MySql and Postgres.

MySql:
```scala

[error] Test com.typesafe.slick.testkit.tests.JoinTest.testDiscriminatorCheck[mysql] failed: java.lang.AssertionError: expected:<Set(3)> but was:<Set()>, took 0.024 sec
[error]     at com.typesafe.slick.testkit.tests.JoinTest$$anonfun$testDiscriminatorCheck$2.apply(JoinTest.scala:347)
[error]     at com.typesafe.slick.testkit.tests.JoinTest$$anonfun$testDiscriminatorCheck$2.apply(JoinTest.scala:347)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error]     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Postgres:
```scala
[error] Test com.typesafe.slick.testkit.tests.ModelBuilderTest.test[postgres] failed: java.lang.NumberFormatException: For input string: "'-5'::integer", took 0.413 sec
[error]     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error]     at java.lang.Integer.parseInt(Integer.java:569)
[error]     at java.lang.Integer.parseInt(Integer.java:615)
[error]     at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
[error]     at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:220)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:214)
[error]     at scala.Option.map(Option.scala:146)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder.default(JdbcModelBuilder.scala:214)
[error]     at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.slick$jdbc$PostgresProfile$ModelBuilder$$anon$$super$default(PostgresProfile.scala:86)
[error]     at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2$$anonfun$default$3.apply(PostgresProfile.scala:86)
[error]     at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2$$anonfun$default$3.apply(PostgresProfile.scala:85)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.default(PostgresProfile.scala:85)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:253)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:263)
[error]     at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:281)
[error]     at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
[error]     at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error]     at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]     at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:163)
[error]     at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:163)
[error]     at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:161)
[error]     at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
[error]     at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error]     at scala.collection.immutable.List.map(List.scala:285)
[error]     at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:96)
[error]     at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:93)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error]     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```